title: El Masry # your name (or website title) here
logo: "/Foto.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Scientist with a solid foundation in quantitative social research (Master's degree) and proficiency in applying advanced machine learning techniques. Proficient in programming and data analysis using Python, R, and SQL. Specialized in capturing and interpreting large datasets to optimize customer behavior and business strategies. Robust academic background with a double Bachelor's degree in Political Science and Near and Middle Eastern Studies. Passionate about enhancing business processes through data-driven decision-making.
 
  <br><br>
  <a href="https://www.linkedin.com/in/sharif-el-masry-75312725a">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
