title: El Masry # your name (or website title) here
logo: "/Foto.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Expert Data Scientist with a deep dive in machine learning and a strong foundation in quantitative social research. Proficient in Python, R, and SQL. Passionate about leveraging vast datasets to drive business decisions and optimize customer behavior.

 
  <br><br>
  <a href="https://www.linkedin.com/in/sharif-el-masry-75312725a">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
